### ISSUE TITLE
disable "Illuminate All" and "Extinguish All"?

### ISSUE THREAD

**Issue by garyhooper** [tagyoureit/homebridge-luxor#20]
Is there a way to disable the automatic creation of "Illuminate All" and "Extinguish All"?

Thanks for the plug-in!

**Comment by tagyoureit** [comment]
I just added a config entry to skip the creation of those themes.  Pull 4.2.4.  I didn't test it out so lmk if you have any issues.

**Comment by garyhooper** [comment]
I've installed 4.2.4, but do not see the new entry.

![luxor](https://user-images.githubusercontent.com/11620531/183320439-34ee4383-8ed0-422f-ae23-880c361328e0.png)
.

**Comment by garyhooper** [comment]
Logically, it works. I added "noAllThemes" to the json config, and it worked as expected.

There should be something in Settings for this, and I had to manually update dist/LuxorPlatform.js to correspond to the source file (a build is required).

Thanks!

**Comment by tagyoureit** [comment]
Yes, I messed up a copy/paste on the config file and added the dist files.  Force a pull with the same version and it should be resolved.

**Comment by garyhooper** [comment]
For whatever reason, `npm install --force homebridge-luxor` downloads version 4.2.4 from Github, but still shows the version from 2 days ago.

Having said that, the code looks correct.  Can you bump the version?

**Comment by tagyoureit** [comment]
4.2.5 published.

**Comment by garyhooper** [comment]
Excellent...thank you!
